### ISSUE TITLE
Downloader argument to deselect 'parties and counsel'

### ISSUE THREAD

**Issue by nadahlberg** [scales-okn/PACER-tools#1]
For cost saving purposes it would be helpful to be able to deselct and omit parties and counsel from the docket when using the downloader.  Maybe omitting parties should even be the default when docket-update=True.

![Screen Shot 2020-11-30 at 10 23 49 AM](https://user-images.githubusercontent.com/58701810/100628880-b1b98080-32f6-11eb-8c99-075170818e91.png)

**Comment by mangangreg** [comment]
Agreed, omitting parties and council this is a good option for cost saving purposes. The updates in commit https://github.com/scales-okn/PACER-tools/commit/5a170f900df41e6395507023d52069bd24a3ce5f includes this functionality as a command-line option.

As per the updated [downloader readme](https://github.com/scales-okn/PACER-tools/tree/master/code/downloader):

> `--docket-exclude-parties` If True, 'Parties and counsel' and 'Terminated parties' will be excluded from docket reports (this reduces the page count for the docket report so can reduce costs).

This does not become default behavior when running in update mode but to achieve that behavior you can just pass:
 ` --docket-update --docket-exclude-parties`
