### ISSUE TITLE
Bug Report - Missing parse_summary.py Module in Parser

### ISSUE THREAD

**Issue by dn1** [scales-okn/PACER-tools#3]
Hi all, I'm attempting to run the parser on a Windows machine as part of the getting started in the repo readme. I've successfully run the query scraper and docket scraper and cd'd into `code/parsers`. It looks like the `parse_summary` module was not part of the latest commit. See the screenshot below. Am I just looking in the wrong place? Thanks very much!
![image](https://user-images.githubusercontent.com/30941349/149588768-67c0fdb1-7a11-411e-9781-7cfc09f3ca3b.png)

**Comment by mangangreg** [comment]
Hi there! Glad to hear you have been using the scraper. Apologies, there was a missing dependency for the parser, which has just been added in the latest commit https://github.com/scales-okn/PACER-tools/commit/9520d2252d9e6f6f9ad54f7ae930b6451825d6f7 

That should fix the issue, if you have any other related issues we'd be happy to help!
