### ISSUE TITLE
Chunk Error When Running Queries with Case Numbers on Windows Machine

### ISSUE THREAD

**Issue by dn1** [scales-okn/PACER-tools#5]
Hello - I'm running the scraper on a Windows 10 machine and have been able to get the tutorial query working. 

However, when I try to build my own query with a single case number either through this command `python scrapers.py -a login/demo.auth -m query -c psc --override-time -qc test.json ../../data/pacer/psc` or through the CLI query builder, I run into a chunk error. See the screenshots of the logs below.

Chunk error with config json
![image](https://user-images.githubusercontent.com/30941349/152069097-79c5314a-cadf-4c75-bc97-78cc2e108154.png)
Chunk error with CLI query builder
![image](https://user-images.githubusercontent.com/30941349/152069164-5f37b117-7172-4a1a-8fc4-7deb9f5f0125.png)

I have been able to successfully run the query scraper when using `case_status`, `filed_from`, and `filed_to` and also just `case_status` and `last_name` as parameters. These seem to work because they return several results, instead of just one.

What am I missing here? Is it currently not possible to run a query on a single (or list) of case numbers because there is an issue when only one result is returned? Thanks again for all your help - I greatly appreciate it.

**Comment by scottgdaniel** [comment]
Hi there! It looks like you may be attempting to scrape PACER query pages in a situation when you actually want to scrape case dockets. The typical input to the query scraper is a set of open-ended search parameters (date, name, case status, etc) and the output is a list of case numbers returned by the PACER search app. The docket scraper, on the other hand, takes one or more case numbers as input, and outputs the corresponding docket files.

In other words, the purpose of generating and scraping PACER query pages is to create lists of case numbers that you might want to investigate later. If you already know the case numbers you're looking for, you can skip directly to the docket scraper! (To be clear, you are technically "running a PACER query" even when using the docket scraper to grab cases, but we've reserved the name "query scraper" for the script that downloads long-form PACER search results.)


To scrape the case with number 1:07-cr-00003, I created an input file 'test.csv' that looks like this:
<img width="141" alt="Screen Shot 2022-02-02 at 10 48 58 AM" src="https://user-images.githubusercontent.com/30511646/152199088-d1b2652c-1c08-4ef5-b90c-75e72f45287c.png">

Then I ran the following command (with temp/psc being my output directory):
<img width="730" alt="Screen Shot 2022-02-02 at 10 50 53 AM" src="https://user-images.githubusercontent.com/30511646/152199386-e83f7514-669f-4509-afd3-3d2bc3ad5ffb.png">

And I received the following output:
<img width="1428" alt="Screen Shot 2022-02-02 at 10 24 43 AM" src="https://user-images.githubusercontent.com/30511646/152199632-5c385645-b65d-4a06-b6db-a2a24a54ba4b.png">

Let me know if this works for you!

**Comment by dn1** [comment]
Thanks so much - your explanation really clears things up for me! The .csv with a list of ucids works like a charm.
