### ISSUE TITLE
find_element_by_css removed?

### ISSUE THREAD

**Issue by lanedsmu** [scales-okn/PACER-tools#7]
It appears the find_element_by_css function has been removed in the later Selenium releases, so we've reverted back to selenium 4.2.0 in our setup.  Is it possible to replace the find_element_by_css function with a newer function?  I've made a few passes at making that change, but I've not had any luck yet.

**Comment by scottgdaniel** [comment]
Hello Lane,

Hope all is well - apologies for the delay in responding, and thanks for pointing this out! The `find_element_by_css_selector(...)` and similar functions are indeed deprecated in Selenium 4, so I've replaced them with the equivalent `find_element(By.CSS_SELECTOR, ...)` function, which seems to work in all versions of Selenium. I just pushed a fix; let me know if you experience any further issues.

All best,
Scott
